"""The model card for one named run, generated from what the run recorded.

Every number and every label on the card is read from the run's own records
and its verified analysis outputs: `run.json`, `training_metadata.json`,
`threshold.json`, `metrics.json`, the analysis JSONs and, when the run has
one, its `quality_report.json`. Nothing about a dataset is written into the
card by hand, because a card generated for one dataset is read as describing
another.

The card states what was measured and under which conditions. Interpreting
the numbers, and comparing runs, is left to the documents written once
results exist.
"""
from __future__ import annotations

from collections.abc import Iterable, Mapping, Sequence
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from ml.analysis import BUCKET_ORDER
from ml.reporting import (
    OPERATING_THRESHOLD_SOURCE,
    SEGMENT_TEST_ROC_CURVE_SOURCE,
    TEST_ROC_CURVE_SOURCE,
)
from ml.run_verification import RecordedRun
from ml.runs import SplitPeriod

RUN_CARD_FILENAME = "MODEL_CARD.md"

_THRESHOLD_LABELS = {
    OPERATING_THRESHOLD_SOURCE: "operating threshold selected on the validation fold",
    TEST_ROC_CURVE_SOURCE: "point on the test ROC curve",
    SEGMENT_TEST_ROC_CURVE_SOURCE: "point on the segment's own test ROC curve",
}

# The limitations the methodology accepts rather than engineers away, stated
# on every card. The label-delay note is added from the run's own metrics.
_ACCEPTED_LIMITATIONS = (
    "The same card or customer appears in several folds with different transactions. This "
    "matches production, which scores cards it already knows; a held-out-cards evaluation "
    "is future work.",
    "The val fold is used both for early stopping and for threshold selection, so the "
    "realised val FPR is slightly optimistic. The test fold is untouched by both.",
)


def build_run_card(
    recorded: RecordedRun,
    *,
    calibration: Mapping[str, Any],
    feature_importance: Mapping[str, Any],
    segments: Mapping[str, Any],
    quality_report: Mapping[str, Any] | None,
    generated_at: str,
    code_version: str | None,
) -> str:
    """Compose the card's Markdown from the run's records and analysis outputs."""
    sections = [
        _header(recorded, generated_at, code_version),
        _data_section(recorded),
        _folds_section(recorded),
        _fit_section(recorded),
        _threshold_section(recorded),
        _results_section(recorded),
        _calibration_section(calibration),
        _importance_section(recorded, feature_importance),
        _segments_section(segments),
        _quality_section(quality_report),
        _limitations_section(recorded),
    ]
    return "\n\n".join(sections) + "\n"


def write_run_card(recorded: RecordedRun, card: str) -> Path:
    """Write `card` into the run's own directory, the only place a run card goes."""
    path = recorded.directory / RUN_CARD_FILENAME
    path.write_text(card, encoding="utf-8")
    return path


# ---------------------------------------------------------------------------
# Sections
# ---------------------------------------------------------------------------


def _header(recorded: RecordedRun, generated_at: str, code_version: str | None) -> str:
    return "\n".join(
        [
            f"# Model card — run `{recorded.name}`",
            "",
            f"> Generated by `python -m ml.analyze --run-name {recorded.name}` from the records "
            "and verified analysis in this run directory. Do not hand-edit it; re-run the "
            "analysis instead.",
            f"> Generated at `{generated_at}` by code `{code_version or 'not recorded'}`.",
            "",
            "This card describes this run alone. Its methodology is fixed in "
            "`docs/adr/PHASE_5D_BENCHMARK_METHODOLOGY.md`.",
        ]
    )


def _data_section(recorded: RecordedRun) -> str:
    dataset = recorded.record.dataset
    subsample = dataset.subsample
    rows = [
        (
            "Dataset",
            f"`{dataset.name}` version `{dataset.version}` ({dataset.origin.value} origin)",
        ),
        ("Source", dataset.source_url or "—"),
        ("Citation", dataset.citation),
        ("Licence", dataset.license),
        ("Label", f"`{dataset.label_field}`: {dataset.label_definition}"),
        ("Rows", _count_with_frauds(dataset.row_count, dataset.fraud_count)),
        ("Period", f"{_instant(dataset.period_start)} → {_instant(dataset.period_end)}"),
        (
            "Subsample",
            "none recorded"
            if subsample is None
            else (
                f"strategy `{subsample.strategy}`, seed {subsample.seed}, "
                f"at most {_or_dash(subsample.max_entities)} entities, "
                f"{_or_dash(subsample.selected_entities)} selected"
            ),
        ),
        ("Featureset", f"`{recorded.record.featureset_version}`"),
        ("Training code", f"`{recorded.record.code_version or 'not recorded'}`"),
        (
            "Libraries",
            ", ".join(
                f"{name} {version}"
                for name, version in sorted(recorded.record.library_versions.items())
            ),
        ),
    ]
    parts = ["## 1. Data and provenance", "", _table(("", ""), rows)]
    if dataset.files:
        parts += ["", "Source files (SHA-256):", ""]
        parts += [f"- `{name}`: `{digest}`" for name, digest in sorted(dataset.files.items())]
    if dataset.preprocessing:
        parts += ["", "Preprocessing:", ""]
        parts += [f"- {step}" for step in dataset.preprocessing]
    notes = [note for note in (dataset.notes, recorded.record.notes) if note]
    if notes:
        parts += ["", *notes]
    return "\n".join(parts)


def _folds_section(recorded: RecordedRun) -> str:
    metadata = recorded.training_metadata
    fraud_counts = recorded.metrics["context"]["fraud_counts"]
    periods = {period.name: period for period in recorded.record.splits}
    rows = []
    for name in ("train", "val", "test"):
        period: SplitPeriod | None = periods.get(name)
        size = int(metadata[f"{name}_size"])
        frauds = int(fraud_counts[name])
        rows.append(
            (
                name,
                _instant(None if period is None else period.start),
                _instant(None if period is None else period.end),
                f"{size:,}",
                f"{frauds:,}",
                _number(frauds / size if size else None),
            )
        )
    return "\n".join(
        [
            "## 2. Folds",
            "",
            "Chronological 70/15/15 split by row count. Transactions that share a timestamp "
            "may fall on both sides of a boundary.",
            "",
            _table(("Fold", "First (UTC)", "Last (UTC)", "Rows", "Frauds", "Fraud rate"), rows),
        ]
    )


def _fit_section(recorded: RecordedRun) -> str:
    metadata = recorded.training_metadata
    hyperparameters = ", ".join(
        f"`{name}={value}`" for name, value in sorted(metadata["best_hyperparameters"].items())
    )
    best = int(metadata["best_iteration"])
    rows = [
        (
            "Hyperparameter search",
            f"{metadata.get('tuning_iterations', '—')} iterations over "
            f"{metadata.get('tuning_cv_folds', '—')} stratified folds of the training fold, "
            f"random state {metadata.get('random_state', '—')}",
        ),
        (
            "Cross-validated PR-AUC",
            f"{_number(recorded.metrics.get('best_cv_pr_auc'))} — a diagnostic from folds "
            "shuffled within the training period, not a held-out estimate",
        ),
        ("Chosen hyperparameters", hyperparameters or "—"),
        ("scale_pos_weight", _number(metadata.get("scale_pos_weight"))),
        (
            "Early stopping",
            f"after {metadata.get('early_stopping_rounds', '—')} rounds without improvement on "
            f"the val fold; best round {best}, so the saved model holds {best + 1} rounds",
        ),
    ]
    parts = ["## 3. Fit", "", _table(("Setting", "Value"), rows), "", _live_features(recorded)]
    return "\n".join(parts)


def _live_features(recorded: RecordedRun) -> str:
    metadata = recorded.training_metadata
    total = len(recorded.feature_list)
    live = metadata.get("live_feature_count")
    if live is None:
        return "Live features were not recorded for this run."
    constant = list(metadata.get("constant_features") or [])
    sentence = (
        f"**Live features:** {live} of {total} take more than one distinct value in the "
        "training fold. "
        + (
            f"Constant there: {_names(constant)}."
            if constant
            else "None is constant there."
        )
    )
    whole = metadata.get("live_feature_count_whole_matrix")
    if whole is not None and whole != live:
        sentence += (
            f" Over the whole matrix {whole} of {total} are live; constant there: "
            f"{_names(list(metadata.get('constant_features_whole_matrix') or [])) or 'none'}."
        )
    return sentence


def _threshold_section(recorded: RecordedRun) -> str:
    threshold = recorded.threshold
    fallback = {True: "yes", False: "no", None: "not recorded"}[threshold.fallback_used]
    rows = [
        ("Threshold", _number(threshold.value)),
        ("Target FPR on the val fold", _number(threshold.target_fpr)),
        ("Realised FPR on the val fold", _number(threshold.realised_fpr_on_val)),
        ("Fallback used", fallback),
    ]
    parts = [
        "## 4. Operating threshold — selected on the validation fold",
        "",
        "Chosen on the val fold before the test fold was scored (`threshold.json`).",
        "",
        _table(("", ""), rows),
    ]
    if threshold.fallback_used:
        parts += [
            "",
            "No val-fold threshold met the target FPR, so the threshold is the fixed fallback, "
            "not one selected for the target.",
        ]
    return "\n".join(parts)


def _results_section(recorded: RecordedRun) -> str:
    metrics = recorded.metrics
    context = metrics["context"]
    sources = metrics.get("threshold_source", {})
    test_rows = int(recorded.training_metadata["test_size"])
    fraud_counts = context["fraud_counts"]
    prevalence = _number(context["test_prevalence"])
    at_threshold = metrics["at_operating_threshold"]

    rows = [
        (
            "PR-AUC",
            _number(metrics["test_pr_auc"]),
            f"threshold-free; test prevalence {prevalence}",
        ),
        ("ROC-AUC", _number(metrics["test_roc_auc"]), "threshold-free"),
        (
            "Recall @ 1% FPR",
            _number(metrics["recall_at_1pct_fpr"]),
            _threshold_label(sources.get("recall_at_1pct_fpr")),
        ),
        (
            "Recall @ 5% FPR",
            _number(metrics["recall_at_5pct_fpr"]),
            _threshold_label(sources.get("recall_at_5pct_fpr")),
        ),
    ]
    confusion_rows = [
        (
            _number(at_threshold["threshold"]),
            _number(at_threshold["precision"]),
            _number(at_threshold["recall"]),
            _number(at_threshold["f1"]),
            str(at_threshold["true_positives"]),
            str(at_threshold["false_positives"]),
            str(at_threshold["true_negatives"]),
            str(at_threshold["false_negatives"]),
            _number(context["realised_fpr_on_test_at_operating_threshold"]),
        )
    ]
    return "\n".join(
        [
            "## 5. Test-fold results",
            "",
            "The results training recorded for the test fold, reproduced exactly from the "
            f"saved model before this card was written: {test_rows:,} rows, "
            f"{fraud_counts['test']:,} frauds, test prevalence {prevalence}. A PR-AUC is read "
            "against the prevalence: a scorer with no signal scores about the prevalence.",
            "",
            _table(("Result", "Value", "Threshold"), rows),
            "",
            "Each recall at a fixed FPR is read at a threshold found on the test fold itself, so "
            "it is a point on the test ROC curve, not a result at a threshold fixed in advance.",
            "",
            f"At the {_threshold_label(sources.get('at_operating_threshold'))} "
            "(`threshold.json`):",
            "",
            _table(
                (
                    "Threshold",
                    "Precision",
                    "Recall",
                    "F1",
                    "TP",
                    "FP",
                    "TN",
                    "FN",
                    "Realised test FPR",
                ),
                confusion_rows,
            ),
            "",
            f"**Fraud counts:** train {fraud_counts['train']:,}, val {fraud_counts['val']:,}, "
            f"test {fraud_counts['test']:,}.",
            "",
            f"**Label delay:** {context['label_delay_note']}",
        ]
    )


def _calibration_section(calibration: Mapping[str, Any]) -> str:
    counts = calibration["bin_counts"]
    positives = calibration["bin_positive_counts"]
    predicted = calibration["bin_mean_predicted"]
    observed = calibration["bin_mean_observed"]
    width = 1.0 / len(counts) if counts else 0.0
    bins = [
        (
            str(index),
            f"{index * width:.1f} to {(index + 1) * width:.1f}",
            f"{count:,}",
            f"{frauds:,}",
            _number(mean_score) if count else "—",
            _number(fraud_rate) if count else "—",
        )
        for index, (count, frauds, mean_score, fraud_rate) in enumerate(
            zip(counts, positives, predicted, observed, strict=True)
        )
    ]
    rows = [
        (
            "Brier score",
            _number(calibration["brier_score"]),
            _number(calibration["positive_class_brier"]),
        ),
        (
            "Expected calibration error",
            _number(calibration["expected_calibration_error"]),
            _number(calibration["positive_class_ece"]),
        ),
    ]
    parts = [
        "## 6. Calibration — test fold, no calibrator fitted",
        "",
        f"{calibration['note']} {calibration['n_test_samples']:,} test rows.",
        "",
        _table(("Metric", "All test rows", "Positive-class variant"), rows),
        "",
        _table(("Bin", "Score range", "Rows", "Frauds", "Mean score", "Fraud rate"), bins),
    ]
    worst = calibration.get("worst_positive_bin")
    if worst is not None:
        parts += [
            "",
            f"Largest gap in a bin holding frauds: bin {worst['bin_index']}, mean score "
            f"{_number(worst['mean_predicted'])} against a fraud rate of "
            f"{_number(worst['mean_observed'])}.",
        ]
    return "\n".join(parts)


def _importance_section(recorded: RecordedRun, importance: Mapping[str, Any]) -> str:
    constant = set(recorded.training_metadata.get("constant_features") or [])
    rows = [
        (
            str(entry["rank"]),
            f"`{entry['feature']}`",
            _number(entry["mean_abs_shap"]),
            "no" if entry["feature"] in constant else "yes",
        )
        for entry in importance["features"]
    ]
    return "\n".join(
        [
            "## 7. Global feature importance — test fold",
            "",
            f"Mean absolute SHAP value of each feature over the {importance['n_test_samples']:,} "
            f"test rows, in {importance['units']}.",
            "",
            _table(("Rank", "Feature", f"Mean abs SHAP ({importance['units']})", "Live"), rows),
        ]
    )


def _segments_section(segments: Mapping[str, Any]) -> str:
    if not segments.get("reported"):
        groups = ", ".join(
            f"{name}: {count:,}" for name, count in _in_group_order(segments["country_groups"])
        )
        return "\n".join(
            [
                "## 8. Segments",
                "",
                f"Not reported. {segments['reason']}",
                "",
                f"Test rows by country group: {groups or 'none'}.",
            ]
        )

    label = _threshold_label(segments["threshold_source"]["recall_at_1pct_fpr"])
    blocks = [("All test rows", segments["global"]), *_in_group_order(segments["segments"])]
    rows = [
        (
            name,
            f"{block['n_transactions']:,}",
            f"{block['n_frauds']:,}",
            f"{block['n_negatives']:,}",
            _number(block["fraud_rate"]),
            _number(block["pr_auc"]),
            _number(block["recall_at_1pct_fpr"]),
            block.get("skipped_reason", ""),
        )
        for name, block in blocks
    ]
    return "\n".join(
        [
            "## 8. Segments — by country group",
            "",
            _table(
                (
                    "Segment",
                    "Rows",
                    "Frauds",
                    "Legitimate",
                    "Fraud rate",
                    "PR-AUC",
                    f"Recall @ 1% FPR ({label})",
                    "Not measured because",
                ),
                rows,
            ),
            "",
            segments["notes"],
        ]
    )


def _quality_section(report: Mapping[str, Any] | None) -> str:
    if report is None:
        return "## 9. Data quality\n\nNo `quality_report.json` in this run directory."

    rows_record = report["rows"]
    label = report["label"]
    period = report["period"]
    entities = report["entities"]
    rows = [
        ("Rows read", f"{rows_record['raw']:,}"),
        ("Rows kept", f"{rows_record['kept']:,}"),
        ("Rows excluded", f"{rows_record['excluded']:,}"),
        ("Frauds kept", f"{label['fraud_count']:,} (rate {_number(label['fraud_rate'])})"),
        ("Period", f"{period['start'] or '—'} → {period['end'] or '—'}"),
        ("Customers / merchants", f"{entities['customers']:,} / {entities['merchants']:,}"),
    ]
    offsets = report.get("extra", {}).get("unix_time_offset_distribution")
    if offsets is not None:
        rows.append(
            (
                "Distinct unix_time offsets",
                f"{offsets['distinct_offsets']:,} (listing truncated: "
                f"{'yes' if offsets['truncated'] else 'no'})",
            )
        )
    parts = [
        "## 9. Data quality",
        "",
        f"From `quality_report.json`, generated at `{report['generated_at_utc']}`.",
        "",
        _table(("", ""), rows),
    ]
    exclusions = [record for record in report.get("exclusions", []) if record["count"]]
    if exclusions:
        parts += ["", "Excluded rows:", ""]
        parts += [f"- {record['count']:,}: {record['reason']}" for record in exclusions]
    constant_fields = report.get("constant_fields") or {}
    if constant_fields:
        parts += ["", "Constant canonical fields:", ""]
        parts += [f"- `{name}` = `{value}`" for name, value in sorted(constant_fields.items())]
    warnings = report.get("warnings") or []
    if warnings:
        parts += ["", "Warnings:", ""]
        parts += [f"- {warning}" for warning in warnings]
    return "\n".join(parts)


def _limitations_section(recorded: RecordedRun) -> str:
    limitations = [
        *_ACCEPTED_LIMITATIONS,
        f"Label delay: {recorded.metrics['context']['label_delay_note']}",
    ]
    return "\n".join(
        ["## 10. Accepted limitations", "", *(f"- {limitation}" for limitation in limitations)]
    )


# ---------------------------------------------------------------------------
# Formatting
# ---------------------------------------------------------------------------


def _table(header: Sequence[str], rows: Iterable[Sequence[str]]) -> str:
    lines = [
        "| " + " | ".join(header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]
    lines += ["| " + " | ".join(row) + " |" for row in rows]
    return "\n".join(lines)


def _number(value: Any) -> str:
    """Four decimals, or a dash where a value is undefined."""
    return "—" if value is None else f"{float(value):.4f}"


def _or_dash(value: int | None) -> str:
    return "—" if value is None else f"{value:,}"


def _count_with_frauds(rows: int | None, frauds: int | None) -> str:
    if rows is None:
        return "—"
    if frauds is None:
        return f"{rows:,}"
    return f"{rows:,}, of which {frauds:,} fraud (rate {_number(frauds / rows if rows else None)})"


def _instant(value: datetime | None) -> str:
    return "—" if value is None else value.astimezone(UTC).isoformat()


def _names(names: Sequence[str]) -> str:
    return ", ".join(f"`{name}`" for name in names)


def _in_group_order(by_group: Mapping[str, Any]) -> list[tuple[str, Any]]:
    """Country groups in their defined order, whatever order the mapping holds them in.

    The analysis JSONs are written with sorted keys, so the order a mapping
    arrives in says nothing; the card reads the same from memory or from disk.
    """
    rank = {name: index for index, name in enumerate(BUCKET_ORDER)}
    return sorted(by_group.items(), key=lambda item: (rank.get(item[0], len(rank)), item[0]))


def _threshold_label(source: str | None) -> str:
    if source is None:
        return "threshold source not recorded"
    return _THRESHOLD_LABELS.get(source, source)
