"""create initial schema: customers, merchants, transactions, audit_log

Revision ID: 4e0e08a83d4d
Revises: 
Create Date: 2026-05-20 12:27:12.948300+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e0e08a83d4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=False),
    sa.Column('payload', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('ix_audit_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_audit_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('risk_tier', sa.String(length=16), nullable=False),
    sa.Column('account_age_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("risk_tier IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_customers_risk_tier'),
    sa.CheckConstraint('length(country) = 2', name='ck_customers_country_iso2'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('merchants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('mcc', sa.String(length=4), nullable=False),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('risk_rating', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("risk_rating IN ('LOW', 'MEDIUM', 'HIGH')", name='ck_merchants_risk_rating'),
    sa.CheckConstraint('length(country) = 2', name='ck_merchants_country_iso2'),
    sa.CheckConstraint('length(mcc) = 4', name='ck_merchants_mcc_length'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idempotency_key', sa.String(length=128), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('merchant_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=19, scale=4), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('payment_method', sa.String(length=32), nullable=False),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('device_id', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=False),
    sa.Column('is_card_present', sa.Boolean(), nullable=False),
    sa.Column('fraud_score', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('fraud_decision', sa.String(length=16), nullable=True),
    sa.Column('rules_triggered', sa.Text(), nullable=True),
    sa.Column('top_features', sa.Text(), nullable=True),
    sa.Column('analyst_label', sa.String(length=32), nullable=True),
    sa.Column('analyst_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("analyst_label IS NULL OR analyst_label IN ('CONFIRMED_FRAUD', 'CONFIRMED_LEGIT')", name='ck_transactions_analyst_label'),
    sa.CheckConstraint("fraud_decision IS NULL OR fraud_decision IN ('APPROVE', 'REVIEW', 'DECLINE')", name='ck_transactions_fraud_decision'),
    sa.CheckConstraint("status IN ('APPROVED', 'DECLINED', 'PENDING_REVIEW')", name='ck_transactions_status'),
    sa.CheckConstraint('amount > 0', name='ck_transactions_amount_positive'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customer_id', 'idempotency_key', name='uq_transactions_idempotency')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index('ix_transactions_created_at', ['created_at'], unique=False)
        batch_op.create_index('ix_transactions_customer_created', ['customer_id', 'created_at'], unique=False)
        batch_op.create_index('ix_transactions_fraud_decision', ['fraud_decision'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_fraud_decision')
        batch_op.drop_index('ix_transactions_customer_created')
        batch_op.drop_index('ix_transactions_created_at')

    op.drop_table('transactions')
    op.drop_table('merchants')
    op.drop_table('customers')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_resource')
        batch_op.drop_index('ix_audit_created_at')

    op.drop_table('audit_log')
    # ### end Alembic commands ###